### ISSUE TITLE
Core gameplay (Character controller)

### ISSUE THREAD

**Issue by YDenker** [VoIarion/DPL5000gpr.S1#2]
Code for controlling the 2D characters in single-player and/or coop mode, especially the movement outside of combat.
Also includes Interaction and access to inventory and other information windows for the character.
Input via controller and mouse/keyboard.

**Comment by M2-TE** [comment]
Character Controller for basic movement complete.

**Comment by M2-TE** [comment]
Extended Character Controller with virtual override capabilities added.

**Comment by YDenker** [comment]
I would outsource the inputs for the CharacterController to a separate InputManager. This adds comprehensibility and we have all the inputs in a single place. We also can disable inputs for certain scripts much easier when they are not needed. I'd like to hear your thoughts!

**Comment by M2-TE** [comment]
Thanks for your feedback, though the inputs are already being handled via the Unity InputManager, which gives it sufficient overall flexibility for cross-platform or varying desktop-environments.

**Comment by M2-TE** [comment]
urmomgaylol

**Comment by M2-TE** [comment]
Working on a new Character Controller alltogether.

**Comment by YDenker** [comment]
Complete rework of the Dungeon system require a much smaller controller.
