### ISSUE TITLE
Core gameplay (combat)

### ISSUE THREAD

**Issue by YDenker** [VoIarion/DPL5000gpr.S1#6]
The base mechanics behind the round based fighting in the game.
Comparable to the gameplay in "Darkest Dungeon".
Complex stats and statmanipulation system with one or more different characters on each side in combat.

**Comment by M2-TE** [comment]
Core combat completed (functions)

**Comment by M2-TE** [comment]
AoE, Combat Effects, Target Selection -> implemented

**Comment by M2-TE** [comment]
We also need an AI for each hostile combatant. A simple conclusive AI for all enemies would suffice for now.

**Comment by YDenker** [comment]
The combat is working as intended.
